substitutions:
  name: p1-reader
  friendly_name: DSMR Reader

esphome:
  name: p1-reader
  platform: ESP8266
  board: d1_mini

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dsmr Fallback Hotspot"
    password: "XXX"

captive_portal:

logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: VERBOSE
  
uart:
  rx_pin: D7
  baud_rate: 115200
  rx_buffer_size: 1500


dsmr:
  request_pin: D5
  request_interval: 15s

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: ${friendly_name} Energy Delivered Tariff 1
      id: Delivered_Tariff1
      state_class: total_increasing
    energy_delivered_tariff2:
      name: ${friendly_name} Energy Delivered Tariff 2
      id: Delivered_Tariff2
      state_class: total_increasing
    energy_returned_tariff1:
      name: ${friendly_name} Energy Returned Tariff 1
      id: Returned_Tariff1
    energy_returned_tariff2:
      name: ${friendly_name} Energy Returned Tariff 2
      id: Returned_Tariff2
    power_delivered:
      name: ${friendly_name} Power Consumed
    power_returned:
      name: ${friendly_name} Power Returned
    electricity_failures:
      name: ${friendly_name} Electricity Failures
    electricity_long_failures:
      name: ${friendly_name} Electricity Long Failures
    voltage_l1:
      name: ${friendly_name} Voltage L1
    voltage_l2:
      name: ${friendly_name} Voltage L2
    voltage_l3:
      name: ${friendly_name} Voltage L3
    current_l1:
      name: ${friendly_name} Current L1
    current_l2:
      name: ${friendly_name} Current L2
    current_l3:
      name: ${friendly_name} Current L3
    power_delivered_l1:
      name: ${friendly_name} Power Delivered L1
    power_delivered_l2:
      name: ${friendly_name} Power Delivered L2
    power_delivered_l3:
      name: ${friendly_name} Power Delivered L3
    power_returned_l1:
      name: ${friendly_name} Power Returned L1
    power_returned_l2:
      name: ${friendly_name} Power Returned L2
    power_returned_l3:
      name: ${friendly_name} Power Returned L3
    gas_delivered_be:
      name: ${friendly_name} Gas Delivered BE
    active_energy_import_current_average_demand:
      name: ${friendly_name} Current Average
    active_energy_import_maximum_demand_running_month:
      name: ${friendly_name} Max Demande Running Month
    active_energy_import_maximum_demand_last_13_months:
      name: ${friendly_name} Max Demande Last 13 months
    # water_delivered:
    #   name: ${friendly_name} Water Delivered

  - platform: wifi_signal
    name: "WiFi Signal Strenght"
    id: wifi_signal_db
    update_interval: 60s

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal (percent)"
    id: wifi_signal_pct
    unit_of_measurement: "Signal %"
    accuracy_decimals: 0
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    entity_category: "diagnostic"

  - platform: template
    name: Energy Delivered Total
    unit_of_measurement: kWh
    lambda: |-
      return (id(Delivered_Tariff1).state + id(Delivered_Tariff2).state);
  - platform: template
    name: Energy Returned Total
    unit_of_measurement: kWh
    lambda: |-
      return (id(Returned_Tariff1).state + id(Returned_Tariff2).state);
    
text_sensor:
  - platform: dsmr
    identification:
      name: ${friendly_name} Identification
    p1_version_be:
      name: ${friendly_name} Version BE
    message_long:
      name: ${friendly_name} Message Long
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "WiFi SSID"
    bssid:
      name: "WiFi BSSID"
